FROM alpine
RUN apk --update upgrade && \
    apk add curl ca-certificates && \
    update-ca-certificates && \
    rm -rf /var/cache/apk/*

# ADD magically un-archieve if it recognised its tar format.
ADD deadyet /

EXPOSE 8080
CMD ["/deadyet"]
